# Generated by Django 4.0 on 2022-01-25 15:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='rate',
            name='rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
