# Generated by Django 4.0 on 2022-01-25 16:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rate_floor_rate_price_rate_rooms_rate_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='sq',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
