# Generated by Django 4.0 on 2022-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_rate_sq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
